CREATE DATABASE MONEYPOOL
USE MONEYPOOL

CREATE TABLE USERINFO(
	UserID VARCHAR(50) NOT NULL PRIMARY KEY,
	UserFirstName VARCHAR(50) NOT NULL,
	UserLastName VARCHAR(50) NOT NULL,
	UserPhoneNumber VARCHAR(11) NOT NULL,
	UserPassword VARCHAR(50) NOT NULL
)
CREATE TABLE ROOM(
	RoomName varchar(20) Not Null,
	RoomID VARCHAR(5) NOT NULL,
	UserID VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USERINFO(UserID),
	RoomCapacity INT NOT NULL,
	RoomAmount INT NOT NULL,
	PRIMARY KEY(RoomID,UserID)
		
)

CREATE TABLE ROOMDETAILS(
	UserID VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES USERINFO(UserID),
	RoomID VARCHAR(5) ,
	RoomAdmin VARCHAR(50),	
	FOREIGN KEY (RoomID,RoomAdmin) REFERENCES ROOM(RoomID,UserID),
	PRIMARY KEY(UserID,RoomID)
)

CREATE TABLE COMMITTEEDETAILS(
	UserID VARCHAR(50) NOT NULL,
	RoomID VARCHAR(5) NOT NULL,
	FOREIGN KEY(UserID,RoomID) REFERENCES ROOMDETAILS(UserID,RoomID),
	CommMonth VARCHAR(3) NOT NULL,
	CommYear VARCHAR(4) NOT NULL,
	PRIMARY KEY (RoomID,CommMonth,CommYear)
)

CREATE TABLE TRANSACTIONS(
	UserID VARCHAR(50) NOT NULL ,
	RoomID VARCHAR(5) NOT NULL,
	FOREIGN KEY(UserID,RoomID) REFERENCES ROOMDETAILS(UserID,RoomID),
	CurrentMonth VARCHAR(3) NOT NULL ,
	CurrentYear VARCHAR(4) NOT NULL,
	TransactionType varchar(8) not null,
	PRIMARY KEY(UserID,RoomID,CurrentMonth,CurrentYear,TransactionType)
)


SELECT * FROM USERINFO
SELECT * FROM ROOM
SELECT * FROM ROOMDETAILS
SELECT * FROM COMMITTEEDETAILS
SELECT * FROM TRANSACTIONS


SELECT * FROM USERINFO
SELECT * FROM ROOM
SELECT * FROM ROOMDETAILS
SELECT * FROM COMMITTEEDETAILS
SELECT * FROM TRANSACTIONS



